apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gmnnrx7wl-go
  janus-idp.io/tekton: gmnnrx7wl-go
  backstage.io/kubernetes-id: gmnnrx7wl-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gmnnrx7wl-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
