apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gmnnrx7wl-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gmnnrx7wl-go 
  name: gmnnrx7wl-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gmnnrx7wl-go 
